# Generated by Django 3.2.4 on 2021-06-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20210617_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'Order statuses'},
        ),
    ]
