# Generated by Django 3.2.4 on 2021-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_rename_location_orderstatus_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'At vendor'), (2, 'Out for delivery'), (3, 'Delivered')]),
        ),
    ]
