# Generated by Django 3.2.4 on 2021-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.IntegerField(choices=[(2, 'Out for delivery'), (3, 'Delivered')]),
        ),
    ]
