# Generated by Django 3.2.4 on 2021-06-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210617_1909'),
        ('delivery', '0009_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser'),
        ),
    ]
