# Generated by Django 3.2.4 on 2021-06-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('max_orders', models.IntegerField(default=10)),
                ('running_dia', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(1, 'Buyer'), (2, 'Vendor'), (3, 'Runner'), (4, 'Hub')]),
        ),
    ]
